// Generated by CoffeeScript 1.9.1
d3.json("data/scatterplot.json", function(weights) {
  var pointcolor, svgscale;
  svgscale = plotframe(weights, {
    chartname: "#scatterplot",
    xlab: "Weight 1",
    ylab: "Weight 2",
    height: 600,
    width: 620,
    pad: {
      bottom: 90,
      left: 100,
      top: 0,
      right: 10,
      scale: 0.05
    },
    tickPadding: 8
  });
  pointcolor = function(d) {
    if (d.sex === "FEMALE") {
      return "hotpink";
    } else {
      return "slateblue";
    }
  };
  return svgscale.svg.selectAll("circle", {
    chartname: "#scatterplot"
  }).data(weights).enter().append("circle").attr("cx", function(d) {
    return svgscale.x(d.x);
  }).attr("cy", function(d) {
    return svgscale.y(d.y);
  }).attr("r", 5).attr("fill", pointcolor).on("mouseover", function() {
    return d3.select(this).transition().attr("fill", "black");
  }).on("mouseover.tooltip", function(d, i) {
    return svgscale.svg.append("text").text(i + 1).attr("id", "tooltip").attr("x", svgscale.x(d.x) + 10).attr("y", svgscale.y(d.y)).attr("fill", "black").attr("opacity", 0).style("font-family", "sans-serif").transition().attr("opacity", 1);
  }).on("mouseout", function(d) {
    d3.select(this).transition().duration(500).attr("fill", pointcolor);
    return d3.selectAll("#tooltip").transition().duration(500).attr("opacity", 0).remove();
  });
});
